### ISSUE TITLE
News on Market page

### ISSUE THREAD

**Issue by ztcric** [ztcric/CS591_Team_Green_Project#40]

**Comment by ztcric** [comment]
Postponed

**Comment by cwille97** [comment]
Work in progress, currently have news data via API I just need to format it nicely into a Widget. Should be finished tomorrow.

**Comment by cwille97** [comment]
Implemented via newsapi.org, gets 10 most recent results for news regarding stocks. Requires source attribution to the newsapi.org which I accomplished with a link button.
