### ISSUE TITLE
Firebase user's watchlist bug fixing

### ISSUE THREAD

**Issue by ztcric** [ztcric/CS591_Team_Green_Project#53]
The added stock is not saved on Firebase for some reason.

**Comment by cwille97** [comment]
I pushed a change to master. When I first wrote the code, I set it up so a new user who registers automatically has a watchlist created (as they should) but I accidentally put that code in login as well as register. This meant that with every login, a new blank watchlist was created. I just removed the code and now the watchlist persists after logout.
